services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    image: ${APP_IMAGE}
    build:
      context: .
      target: prod
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_ENV: production
      APP_NAME: ${APP_NAME}
      APP_PORT: ${APP_PORT}

      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

      JWT_SECRET: ${JWT_SECRET}

      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    networks:
      - internal
      - public
    restart: unless-stopped
    ports:
      - "8080:3000"

  worker:
    image: ${APP_IMAGE}
    build:
      context: .
      target: prod
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_ENV: production

      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

      JWT_SECRET: ${JWT_SECRET}

      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672}
      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE:-orders.exchange}
      RABBITMQ_PROCESS_QUEUE: ${RABBITMQ_PROCESS_QUEUE:-orders.process}
      RABBITMQ_RETRY_QUEUE: ${RABBITMQ_RETRY_QUEUE:-orders.retry}
      RABBITMQ_DLQ_QUEUE: ${RABBITMQ_DLQ_QUEUE:-orders.dlq}
      RABBITMQ_RETRY_DELAY_MS: ${RABBITMQ_RETRY_DELAY_MS:-3000}
      RABBITMQ_MAX_ATTEMPTS: ${RABBITMQ_MAX_ATTEMPTS:-3}
      RABBITMQ_PREFETCH: ${RABBITMQ_PREFETCH:-10}
    networks:
      - internal
    restart: unless-stopped
    command: node dist/main.worker.js



  migrate:
    image: ${APP_IMAGE}
    build:
      context: .
      target: prod
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
      - internal
    command: ["npm", "run", "migration:run:prod"]

  seed:
    image: ${APP_IMAGE}
    build:
      context: .
      target: prod
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
      - internal
    command: ["npm", "run", "seed:prod"]

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - internal
      - public
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pgdata:
  rabbitmqdata:

networks:
  internal:
    internal: true
  public: {}
