import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity('users')
export class UserEntity {
  // Use UUID so IDs are generated by DB (more realistic than Date.now().toString()).
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ type: 'text', unique: true })
  email!: string;

  @Column({ type: 'text', name: 'first_name' })
  firstName!: string;

  // Nullable because last name might be unknown / not required
  @Column({ type: 'text', nullable: true, name: 'last_name' })
  lastName!: string | null;

  // Nullable because phone may be absent
  @Column({ type: 'text', nullable: true })
  phone!: string | null;
}
