import { execSync } from "child_process";

const BOLD = "\x1b[1m";
const GREEN = "\x1b[32m";
const RED = "\x1b[31m";
const YELLOW = "\x1b[33m";
const RESET = "\x1b[0m";

const ok = (msg: string) => console.log(`${GREEN}✓${RESET} ${msg}`);
const fail = (msg: string) => console.error(`${RED}✗${RESET} ${msg}`);
const warn = (msg: string) => console.log(`${YELLOW}!${RESET} ${msg}`);

function parseArgs(args: string[]): { token?: string; backendUrl?: string } {
  const tokenIdx = args.indexOf("--token");
  const backendIdx = args.indexOf("--backend-url");
  return {
    token: tokenIdx !== -1 ? args[tokenIdx + 1] : undefined,
    backendUrl: backendIdx !== -1 ? args[backendIdx + 1] : undefined,
  };
}

function checkClaudeCli(): boolean {
  try {
    execSync("claude --version", { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

function removeOldRegistration(): void {
  try {
    execSync('claude mcp remove "localization" -s user', { stdio: "pipe" });
    ok("Removed old registration");
  } catch {
    // Not registered yet — fine
  }
}

function register(token: string, backendUrl: string): void {
  execSync(
    `claude mcp add "localization" -s user -e MCP_TOKEN=${token} -e BACKEND_URL=${backendUrl} -- npx -y localization-mcp-server`,
    { stdio: "pipe" },
  );
}

async function verifyToken(token: string, backendUrl: string): Promise<boolean> {
  try {
    const response = await fetch(`${backendUrl}/translations/projects`, {
      headers: { Authorization: `Bearer ${token}` },
      signal: AbortSignal.timeout(10_000),
    });
    return response.ok;
  } catch {
    return false;
  }
}

export async function runSetup(args: string[]): Promise<void> {
  console.log(`\n${BOLD}Localization MCP — setup${RESET}\n`);

  const { token, backendUrl = "http://localhost:8080" } = parseArgs(args);

  if (!token) {
    fail("Missing --token. Run the command generated by the admin panel.");
    process.exit(1);
  }

  // 1. Check Claude CLI
  if (!checkClaudeCli()) {
    fail("Claude CLI not found. Install it from https://claude.ai/code");
    process.exit(1);
  }
  ok("Claude CLI found");

  // 2. Remove old registration
  removeOldRegistration();

  // 3. Register with correct token
  try {
    register(token, backendUrl);
    ok("MCP server registered");
  } catch (e) {
    fail(`Failed to register MCP server: ${e}`);
    process.exit(1);
  }

  // 4. Verify token works
  const valid = await verifyToken(token, backendUrl);
  if (!valid) {
    fail("Token verification failed — the token may be expired or the server is unreachable.");
    warn("MCP is registered but will not work until the token is valid.");
    warn("Re-run this command with a fresh token from the admin panel.");
    process.exit(1);
  }
  ok("Token verified");

  console.log(`\n${GREEN}${BOLD}Setup complete.${RESET}`);
  console.log("Restart Claude for the changes to take effect.\n");
}
